
default: exercici1 exercici2 exercici3 exercici4 exercici5 exercici6

exercici1: Exercici1.c
	gcc Exercici1.c -o Exercici1 -lm

exercici2: Exercici2.c
	gcc Exercici2.c -o Exercici2 -lm

exercici3: Exercici3.c
	gcc Exercici3.c -o Exercici3 -lm

exercici4: Exercici4.c
	gcc Exercici4.c -o Exercici4 -lm

exercici5: Exercici5.c
	gcc Exercici5.c -o Exercici5 -lm

exercici6: Exercici6.c
	gcc Exercici6.c -o Exercici6 -lm



